theme: jekyll-theme-cayman
title: Stimulus Write-up
description: A write-up of the reasoning behind choosing Stimulus and our first attempt at using the framework
url: "https://sensei100.github.io/stimulus_writeup/"
